"""add_created_at_to_webhooks

Revision ID: 04ea6abb952e
Revises: eec00295be2f
Create Date: 2025-11-26 17:23:38.935172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ea6abb952e'
down_revision: Union[str, Sequence[str], None] = 'eec00295be2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'created_at')
    # ### end Alembic commands ###
