"""add_name_column_to_product

Revision ID: eec00295be2f
Revises: bf370b830f02
Create Date: 2025-11-26 14:17:16.160058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec00295be2f'
down_revision: Union[str, Sequence[str], None] = 'bf370b830f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE product SET name = sku WHERE name IS NULL")
    op.alter_column('product', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
